### ISSUE TITLE
download addresses and create unique list

### ISSUE THREAD

**Issue by mrcnc** [codefornola/address-autocomplete#2]
Use the list here https://data.nola.gov/Geographic-Base-Layers/Addresses/s4ns-ak5d

**Comment by mrcnc** [comment]
`wget -O addresses.csv https://opendata.arcgis.com/datasets/b7956c8840554a25ae4e35d08b8c17a6_0.csv`

**Comment by mrcnc** [comment]
Here's a python snippet to get the list of addresses into a JS array:

```
import csv
csvfile = open('addresses.csv')
reader = csv.DictReader(csvfile)
addresses = [row['FULLADDR'].upper() for row in reader]
with open('addresses.js', 'w') as output:
    output.write('var addresses = ')
    output.write(str(addresses))
    output.write(';')
```

**Comment by mrcnc** [comment]
Initial work started [here](https://github.com/mrcnc/address-autocomplete/tree/add-trie).  Still a lot of things to do...just updating here in case anyone is interested

**Comment by aaron-junot** [comment]
Cool, I haven't ran the code but I have looked at it. Can I fix the thing about `var _this = this;` using `bind()` or `call()` depending on what's easy and still readable?

**Comment by mrcnc** [comment]
@aaron-suarez...sure...if you can get this working before I get around to it, submit a PR

**Comment by aaron-junot** [comment]
@mrcnc My proposal is the following. Since you haven't committed to codefornola/address-autocomplete, am I expected to do a PR to your fork? Please advise, and I'll do the PR. I just tested it with console.log and it gave me the behavior I expected. Let me know which version you'd like me to use as well. If you go with version 2, please let me know what to name this function, as I'm not entirely sure that "traverse" is even what this function is doing...

Version 1:

```
Object.keys(node.children).forEach(function(key) {
      this.dfs(node.children[key], sofar.concat(key), words);
}.bind(this));
```

Version 2:

```
function traverse (key) {
      this.dfs(node.children[key], sofar.concat(key), words);
}

Object.keys(node.children).forEach(traverse.bind(this));
```

**Comment by mrcnc** [comment]
I'll call this one completed from [#3](https://github.com/codefornola/address-autocomplete/pull/3)
